// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: f1/car_telemetry.proto

package f1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Protocol Buffers - F1 Car Telemetry Data
type CarTelemetry struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Speed                  float32                `protobuf:"fixed32,1,opt,name=speed,proto3" json:"speed,omitempty"`
	Throttle               float32                `protobuf:"fixed32,2,opt,name=throttle,proto3" json:"throttle,omitempty"`
	Brake                  float32                `protobuf:"fixed32,3,opt,name=brake,proto3" json:"brake,omitempty"`
	Gear                   int32                  `protobuf:"varint,4,opt,name=gear,proto3" json:"gear,omitempty"`
	EngineRpm              float32                `protobuf:"fixed32,5,opt,name=engine_rpm,json=engineRpm,proto3" json:"engine_rpm,omitempty"`
	Drs                    float32                `protobuf:"fixed32,6,opt,name=drs,proto3" json:"drs,omitempty"`
	FrontLeftTyrePressure  float32                `protobuf:"fixed32,7,opt,name=front_left_tyre_pressure,json=frontLeftTyrePressure,proto3" json:"front_left_tyre_pressure,omitempty"`
	FrontRightTyrePressure float32                `protobuf:"fixed32,8,opt,name=front_right_tyre_pressure,json=frontRightTyrePressure,proto3" json:"front_right_tyre_pressure,omitempty"`
	RearLeftTyrePressure   float32                `protobuf:"fixed32,9,opt,name=rear_left_tyre_pressure,json=rearLeftTyrePressure,proto3" json:"rear_left_tyre_pressure,omitempty"`
	RearRightTyrePressure  float32                `protobuf:"fixed32,10,opt,name=rear_right_tyre_pressure,json=rearRightTyrePressure,proto3" json:"rear_right_tyre_pressure,omitempty"`
	FrontLeftWheelAngle    float32                `protobuf:"fixed32,11,opt,name=front_left_wheel_angle,json=frontLeftWheelAngle,proto3" json:"front_left_wheel_angle,omitempty"`
	FrontRightWheelAngle   float32                `protobuf:"fixed32,12,opt,name=front_right_wheel_angle,json=frontRightWheelAngle,proto3" json:"front_right_wheel_angle,omitempty"`
	RearLeftWheelAngle     float32                `protobuf:"fixed32,13,opt,name=rear_left_wheel_angle,json=rearLeftWheelAngle,proto3" json:"rear_left_wheel_angle,omitempty"`
	RearRightWheelAngle    float32                `protobuf:"fixed32,14,opt,name=rear_right_wheel_angle,json=rearRightWheelAngle,proto3" json:"rear_right_wheel_angle,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CarTelemetry) Reset() {
	*x = CarTelemetry{}
	mi := &file_f1_car_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarTelemetry) ProtoMessage() {}

func (x *CarTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_f1_car_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarTelemetry.ProtoReflect.Descriptor instead.
func (*CarTelemetry) Descriptor() ([]byte, []int) {
	return file_f1_car_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *CarTelemetry) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *CarTelemetry) GetThrottle() float32 {
	if x != nil {
		return x.Throttle
	}
	return 0
}

func (x *CarTelemetry) GetBrake() float32 {
	if x != nil {
		return x.Brake
	}
	return 0
}

func (x *CarTelemetry) GetGear() int32 {
	if x != nil {
		return x.Gear
	}
	return 0
}

func (x *CarTelemetry) GetEngineRpm() float32 {
	if x != nil {
		return x.EngineRpm
	}
	return 0
}

func (x *CarTelemetry) GetDrs() float32 {
	if x != nil {
		return x.Drs
	}
	return 0
}

func (x *CarTelemetry) GetFrontLeftTyrePressure() float32 {
	if x != nil {
		return x.FrontLeftTyrePressure
	}
	return 0
}

func (x *CarTelemetry) GetFrontRightTyrePressure() float32 {
	if x != nil {
		return x.FrontRightTyrePressure
	}
	return 0
}

func (x *CarTelemetry) GetRearLeftTyrePressure() float32 {
	if x != nil {
		return x.RearLeftTyrePressure
	}
	return 0
}

func (x *CarTelemetry) GetRearRightTyrePressure() float32 {
	if x != nil {
		return x.RearRightTyrePressure
	}
	return 0
}

func (x *CarTelemetry) GetFrontLeftWheelAngle() float32 {
	if x != nil {
		return x.FrontLeftWheelAngle
	}
	return 0
}

func (x *CarTelemetry) GetFrontRightWheelAngle() float32 {
	if x != nil {
		return x.FrontRightWheelAngle
	}
	return 0
}

func (x *CarTelemetry) GetRearLeftWheelAngle() float32 {
	if x != nil {
		return x.RearLeftWheelAngle
	}
	return 0
}

func (x *CarTelemetry) GetRearRightWheelAngle() float32 {
	if x != nil {
		return x.RearRightWheelAngle
	}
	return 0
}

var File_f1_car_telemetry_proto protoreflect.FileDescriptor

const file_f1_car_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x16f1/car_telemetry.proto\x12\x02f1\"\xd3\x04\n" +
	"\fCarTelemetry\x12\x14\n" +
	"\x05speed\x18\x01 \x01(\x02R\x05speed\x12\x1a\n" +
	"\bthrottle\x18\x02 \x01(\x02R\bthrottle\x12\x14\n" +
	"\x05brake\x18\x03 \x01(\x02R\x05brake\x12\x12\n" +
	"\x04gear\x18\x04 \x01(\x05R\x04gear\x12\x1d\n" +
	"\n" +
	"engine_rpm\x18\x05 \x01(\x02R\tengineRpm\x12\x10\n" +
	"\x03drs\x18\x06 \x01(\x02R\x03drs\x127\n" +
	"\x18front_left_tyre_pressure\x18\a \x01(\x02R\x15frontLeftTyrePressure\x129\n" +
	"\x19front_right_tyre_pressure\x18\b \x01(\x02R\x16frontRightTyrePressure\x125\n" +
	"\x17rear_left_tyre_pressure\x18\t \x01(\x02R\x14rearLeftTyrePressure\x127\n" +
	"\x18rear_right_tyre_pressure\x18\n" +
	" \x01(\x02R\x15rearRightTyrePressure\x123\n" +
	"\x16front_left_wheel_angle\x18\v \x01(\x02R\x13frontLeftWheelAngle\x125\n" +
	"\x17front_right_wheel_angle\x18\f \x01(\x02R\x14frontRightWheelAngle\x121\n" +
	"\x15rear_left_wheel_angle\x18\r \x01(\x02R\x12rearLeftWheelAngle\x123\n" +
	"\x16rear_right_wheel_angle\x18\x0e \x01(\x02R\x13rearRightWheelAngleB\x05Z\x03/f1b\x06proto3"

var (
	file_f1_car_telemetry_proto_rawDescOnce sync.Once
	file_f1_car_telemetry_proto_rawDescData []byte
)

func file_f1_car_telemetry_proto_rawDescGZIP() []byte {
	file_f1_car_telemetry_proto_rawDescOnce.Do(func() {
		file_f1_car_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_f1_car_telemetry_proto_rawDesc), len(file_f1_car_telemetry_proto_rawDesc)))
	})
	return file_f1_car_telemetry_proto_rawDescData
}

var file_f1_car_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_f1_car_telemetry_proto_goTypes = []any{
	(*CarTelemetry)(nil), // 0: f1.CarTelemetry
}
var file_f1_car_telemetry_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_f1_car_telemetry_proto_init() }
func file_f1_car_telemetry_proto_init() {
	if File_f1_car_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_f1_car_telemetry_proto_rawDesc), len(file_f1_car_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_f1_car_telemetry_proto_goTypes,
		DependencyIndexes: file_f1_car_telemetry_proto_depIdxs,
		MessageInfos:      file_f1_car_telemetry_proto_msgTypes,
	}.Build()
	File_f1_car_telemetry_proto = out.File
	file_f1_car_telemetry_proto_goTypes = nil
	file_f1_car_telemetry_proto_depIdxs = nil
}
