// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: f1/car_telemetry.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_f1_2fcar_5ftelemetry_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_f1_2fcar_5ftelemetry_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_f1_2fcar_5ftelemetry_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_f1_2fcar_5ftelemetry_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_f1_2fcar_5ftelemetry_2eproto;
namespace f1 {
class CarTelemetry;
struct CarTelemetryDefaultTypeInternal;
extern CarTelemetryDefaultTypeInternal _CarTelemetry_default_instance_;
}  // namespace f1
PROTOBUF_NAMESPACE_OPEN
template<> ::f1::CarTelemetry* Arena::CreateMaybeMessage<::f1::CarTelemetry>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace f1 {

// ===================================================================

class CarTelemetry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:f1.CarTelemetry) */ {
 public:
  inline CarTelemetry() : CarTelemetry(nullptr) {}
  ~CarTelemetry() override;
  explicit PROTOBUF_CONSTEXPR CarTelemetry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CarTelemetry(const CarTelemetry& from);
  CarTelemetry(CarTelemetry&& from) noexcept
    : CarTelemetry() {
    *this = ::std::move(from);
  }

  inline CarTelemetry& operator=(const CarTelemetry& from) {
    CopyFrom(from);
    return *this;
  }
  inline CarTelemetry& operator=(CarTelemetry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CarTelemetry& default_instance() {
    return *internal_default_instance();
  }
  static inline const CarTelemetry* internal_default_instance() {
    return reinterpret_cast<const CarTelemetry*>(
               &_CarTelemetry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CarTelemetry& a, CarTelemetry& b) {
    a.Swap(&b);
  }
  inline void Swap(CarTelemetry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CarTelemetry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CarTelemetry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CarTelemetry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CarTelemetry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CarTelemetry& from) {
    CarTelemetry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CarTelemetry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "f1.CarTelemetry";
  }
  protected:
  explicit CarTelemetry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSpeedFieldNumber = 1,
    kThrottleFieldNumber = 2,
    kBrakeFieldNumber = 3,
    kGearFieldNumber = 4,
    kEngineRpmFieldNumber = 5,
    kDrsFieldNumber = 6,
    kFrontLeftTyrePressureFieldNumber = 7,
    kFrontRightTyrePressureFieldNumber = 8,
    kRearLeftTyrePressureFieldNumber = 9,
    kRearRightTyrePressureFieldNumber = 10,
    kFrontLeftWheelAngleFieldNumber = 11,
    kFrontRightWheelAngleFieldNumber = 12,
    kRearLeftWheelAngleFieldNumber = 13,
    kRearRightWheelAngleFieldNumber = 14,
  };
  // float speed = 1;
  void clear_speed();
  float speed() const;
  void set_speed(float value);
  private:
  float _internal_speed() const;
  void _internal_set_speed(float value);
  public:

  // float throttle = 2;
  void clear_throttle();
  float throttle() const;
  void set_throttle(float value);
  private:
  float _internal_throttle() const;
  void _internal_set_throttle(float value);
  public:

  // float brake = 3;
  void clear_brake();
  float brake() const;
  void set_brake(float value);
  private:
  float _internal_brake() const;
  void _internal_set_brake(float value);
  public:

  // int32 gear = 4;
  void clear_gear();
  int32_t gear() const;
  void set_gear(int32_t value);
  private:
  int32_t _internal_gear() const;
  void _internal_set_gear(int32_t value);
  public:

  // float engine_rpm = 5;
  void clear_engine_rpm();
  float engine_rpm() const;
  void set_engine_rpm(float value);
  private:
  float _internal_engine_rpm() const;
  void _internal_set_engine_rpm(float value);
  public:

  // float drs = 6;
  void clear_drs();
  float drs() const;
  void set_drs(float value);
  private:
  float _internal_drs() const;
  void _internal_set_drs(float value);
  public:

  // float front_left_tyre_pressure = 7;
  void clear_front_left_tyre_pressure();
  float front_left_tyre_pressure() const;
  void set_front_left_tyre_pressure(float value);
  private:
  float _internal_front_left_tyre_pressure() const;
  void _internal_set_front_left_tyre_pressure(float value);
  public:

  // float front_right_tyre_pressure = 8;
  void clear_front_right_tyre_pressure();
  float front_right_tyre_pressure() const;
  void set_front_right_tyre_pressure(float value);
  private:
  float _internal_front_right_tyre_pressure() const;
  void _internal_set_front_right_tyre_pressure(float value);
  public:

  // float rear_left_tyre_pressure = 9;
  void clear_rear_left_tyre_pressure();
  float rear_left_tyre_pressure() const;
  void set_rear_left_tyre_pressure(float value);
  private:
  float _internal_rear_left_tyre_pressure() const;
  void _internal_set_rear_left_tyre_pressure(float value);
  public:

  // float rear_right_tyre_pressure = 10;
  void clear_rear_right_tyre_pressure();
  float rear_right_tyre_pressure() const;
  void set_rear_right_tyre_pressure(float value);
  private:
  float _internal_rear_right_tyre_pressure() const;
  void _internal_set_rear_right_tyre_pressure(float value);
  public:

  // float front_left_wheel_angle = 11;
  void clear_front_left_wheel_angle();
  float front_left_wheel_angle() const;
  void set_front_left_wheel_angle(float value);
  private:
  float _internal_front_left_wheel_angle() const;
  void _internal_set_front_left_wheel_angle(float value);
  public:

  // float front_right_wheel_angle = 12;
  void clear_front_right_wheel_angle();
  float front_right_wheel_angle() const;
  void set_front_right_wheel_angle(float value);
  private:
  float _internal_front_right_wheel_angle() const;
  void _internal_set_front_right_wheel_angle(float value);
  public:

  // float rear_left_wheel_angle = 13;
  void clear_rear_left_wheel_angle();
  float rear_left_wheel_angle() const;
  void set_rear_left_wheel_angle(float value);
  private:
  float _internal_rear_left_wheel_angle() const;
  void _internal_set_rear_left_wheel_angle(float value);
  public:

  // float rear_right_wheel_angle = 14;
  void clear_rear_right_wheel_angle();
  float rear_right_wheel_angle() const;
  void set_rear_right_wheel_angle(float value);
  private:
  float _internal_rear_right_wheel_angle() const;
  void _internal_set_rear_right_wheel_angle(float value);
  public:

  // @@protoc_insertion_point(class_scope:f1.CarTelemetry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float speed_;
    float throttle_;
    float brake_;
    int32_t gear_;
    float engine_rpm_;
    float drs_;
    float front_left_tyre_pressure_;
    float front_right_tyre_pressure_;
    float rear_left_tyre_pressure_;
    float rear_right_tyre_pressure_;
    float front_left_wheel_angle_;
    float front_right_wheel_angle_;
    float rear_left_wheel_angle_;
    float rear_right_wheel_angle_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_f1_2fcar_5ftelemetry_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CarTelemetry

// float speed = 1;
inline void CarTelemetry::clear_speed() {
  _impl_.speed_ = 0;
}
inline float CarTelemetry::_internal_speed() const {
  return _impl_.speed_;
}
inline float CarTelemetry::speed() const {
  // @@protoc_insertion_point(field_get:f1.CarTelemetry.speed)
  return _internal_speed();
}
inline void CarTelemetry::_internal_set_speed(float value) {
  
  _impl_.speed_ = value;
}
inline void CarTelemetry::set_speed(float value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:f1.CarTelemetry.speed)
}

// float throttle = 2;
inline void CarTelemetry::clear_throttle() {
  _impl_.throttle_ = 0;
}
inline float CarTelemetry::_internal_throttle() const {
  return _impl_.throttle_;
}
inline float CarTelemetry::throttle() const {
  // @@protoc_insertion_point(field_get:f1.CarTelemetry.throttle)
  return _internal_throttle();
}
inline void CarTelemetry::_internal_set_throttle(float value) {
  
  _impl_.throttle_ = value;
}
inline void CarTelemetry::set_throttle(float value) {
  _internal_set_throttle(value);
  // @@protoc_insertion_point(field_set:f1.CarTelemetry.throttle)
}

// float brake = 3;
inline void CarTelemetry::clear_brake() {
  _impl_.brake_ = 0;
}
inline float CarTelemetry::_internal_brake() const {
  return _impl_.brake_;
}
inline float CarTelemetry::brake() const {
  // @@protoc_insertion_point(field_get:f1.CarTelemetry.brake)
  return _internal_brake();
}
inline void CarTelemetry::_internal_set_brake(float value) {
  
  _impl_.brake_ = value;
}
inline void CarTelemetry::set_brake(float value) {
  _internal_set_brake(value);
  // @@protoc_insertion_point(field_set:f1.CarTelemetry.brake)
}

// int32 gear = 4;
inline void CarTelemetry::clear_gear() {
  _impl_.gear_ = 0;
}
inline int32_t CarTelemetry::_internal_gear() const {
  return _impl_.gear_;
}
inline int32_t CarTelemetry::gear() const {
  // @@protoc_insertion_point(field_get:f1.CarTelemetry.gear)
  return _internal_gear();
}
inline void CarTelemetry::_internal_set_gear(int32_t value) {
  
  _impl_.gear_ = value;
}
inline void CarTelemetry::set_gear(int32_t value) {
  _internal_set_gear(value);
  // @@protoc_insertion_point(field_set:f1.CarTelemetry.gear)
}

// float engine_rpm = 5;
inline void CarTelemetry::clear_engine_rpm() {
  _impl_.engine_rpm_ = 0;
}
inline float CarTelemetry::_internal_engine_rpm() const {
  return _impl_.engine_rpm_;
}
inline float CarTelemetry::engine_rpm() const {
  // @@protoc_insertion_point(field_get:f1.CarTelemetry.engine_rpm)
  return _internal_engine_rpm();
}
inline void CarTelemetry::_internal_set_engine_rpm(float value) {
  
  _impl_.engine_rpm_ = value;
}
inline void CarTelemetry::set_engine_rpm(float value) {
  _internal_set_engine_rpm(value);
  // @@protoc_insertion_point(field_set:f1.CarTelemetry.engine_rpm)
}

// float drs = 6;
inline void CarTelemetry::clear_drs() {
  _impl_.drs_ = 0;
}
inline float CarTelemetry::_internal_drs() const {
  return _impl_.drs_;
}
inline float CarTelemetry::drs() const {
  // @@protoc_insertion_point(field_get:f1.CarTelemetry.drs)
  return _internal_drs();
}
inline void CarTelemetry::_internal_set_drs(float value) {
  
  _impl_.drs_ = value;
}
inline void CarTelemetry::set_drs(float value) {
  _internal_set_drs(value);
  // @@protoc_insertion_point(field_set:f1.CarTelemetry.drs)
}

// float front_left_tyre_pressure = 7;
inline void CarTelemetry::clear_front_left_tyre_pressure() {
  _impl_.front_left_tyre_pressure_ = 0;
}
inline float CarTelemetry::_internal_front_left_tyre_pressure() const {
  return _impl_.front_left_tyre_pressure_;
}
inline float CarTelemetry::front_left_tyre_pressure() const {
  // @@protoc_insertion_point(field_get:f1.CarTelemetry.front_left_tyre_pressure)
  return _internal_front_left_tyre_pressure();
}
inline void CarTelemetry::_internal_set_front_left_tyre_pressure(float value) {
  
  _impl_.front_left_tyre_pressure_ = value;
}
inline void CarTelemetry::set_front_left_tyre_pressure(float value) {
  _internal_set_front_left_tyre_pressure(value);
  // @@protoc_insertion_point(field_set:f1.CarTelemetry.front_left_tyre_pressure)
}

// float front_right_tyre_pressure = 8;
inline void CarTelemetry::clear_front_right_tyre_pressure() {
  _impl_.front_right_tyre_pressure_ = 0;
}
inline float CarTelemetry::_internal_front_right_tyre_pressure() const {
  return _impl_.front_right_tyre_pressure_;
}
inline float CarTelemetry::front_right_tyre_pressure() const {
  // @@protoc_insertion_point(field_get:f1.CarTelemetry.front_right_tyre_pressure)
  return _internal_front_right_tyre_pressure();
}
inline void CarTelemetry::_internal_set_front_right_tyre_pressure(float value) {
  
  _impl_.front_right_tyre_pressure_ = value;
}
inline void CarTelemetry::set_front_right_tyre_pressure(float value) {
  _internal_set_front_right_tyre_pressure(value);
  // @@protoc_insertion_point(field_set:f1.CarTelemetry.front_right_tyre_pressure)
}

// float rear_left_tyre_pressure = 9;
inline void CarTelemetry::clear_rear_left_tyre_pressure() {
  _impl_.rear_left_tyre_pressure_ = 0;
}
inline float CarTelemetry::_internal_rear_left_tyre_pressure() const {
  return _impl_.rear_left_tyre_pressure_;
}
inline float CarTelemetry::rear_left_tyre_pressure() const {
  // @@protoc_insertion_point(field_get:f1.CarTelemetry.rear_left_tyre_pressure)
  return _internal_rear_left_tyre_pressure();
}
inline void CarTelemetry::_internal_set_rear_left_tyre_pressure(float value) {
  
  _impl_.rear_left_tyre_pressure_ = value;
}
inline void CarTelemetry::set_rear_left_tyre_pressure(float value) {
  _internal_set_rear_left_tyre_pressure(value);
  // @@protoc_insertion_point(field_set:f1.CarTelemetry.rear_left_tyre_pressure)
}

// float rear_right_tyre_pressure = 10;
inline void CarTelemetry::clear_rear_right_tyre_pressure() {
  _impl_.rear_right_tyre_pressure_ = 0;
}
inline float CarTelemetry::_internal_rear_right_tyre_pressure() const {
  return _impl_.rear_right_tyre_pressure_;
}
inline float CarTelemetry::rear_right_tyre_pressure() const {
  // @@protoc_insertion_point(field_get:f1.CarTelemetry.rear_right_tyre_pressure)
  return _internal_rear_right_tyre_pressure();
}
inline void CarTelemetry::_internal_set_rear_right_tyre_pressure(float value) {
  
  _impl_.rear_right_tyre_pressure_ = value;
}
inline void CarTelemetry::set_rear_right_tyre_pressure(float value) {
  _internal_set_rear_right_tyre_pressure(value);
  // @@protoc_insertion_point(field_set:f1.CarTelemetry.rear_right_tyre_pressure)
}

// float front_left_wheel_angle = 11;
inline void CarTelemetry::clear_front_left_wheel_angle() {
  _impl_.front_left_wheel_angle_ = 0;
}
inline float CarTelemetry::_internal_front_left_wheel_angle() const {
  return _impl_.front_left_wheel_angle_;
}
inline float CarTelemetry::front_left_wheel_angle() const {
  // @@protoc_insertion_point(field_get:f1.CarTelemetry.front_left_wheel_angle)
  return _internal_front_left_wheel_angle();
}
inline void CarTelemetry::_internal_set_front_left_wheel_angle(float value) {
  
  _impl_.front_left_wheel_angle_ = value;
}
inline void CarTelemetry::set_front_left_wheel_angle(float value) {
  _internal_set_front_left_wheel_angle(value);
  // @@protoc_insertion_point(field_set:f1.CarTelemetry.front_left_wheel_angle)
}

// float front_right_wheel_angle = 12;
inline void CarTelemetry::clear_front_right_wheel_angle() {
  _impl_.front_right_wheel_angle_ = 0;
}
inline float CarTelemetry::_internal_front_right_wheel_angle() const {
  return _impl_.front_right_wheel_angle_;
}
inline float CarTelemetry::front_right_wheel_angle() const {
  // @@protoc_insertion_point(field_get:f1.CarTelemetry.front_right_wheel_angle)
  return _internal_front_right_wheel_angle();
}
inline void CarTelemetry::_internal_set_front_right_wheel_angle(float value) {
  
  _impl_.front_right_wheel_angle_ = value;
}
inline void CarTelemetry::set_front_right_wheel_angle(float value) {
  _internal_set_front_right_wheel_angle(value);
  // @@protoc_insertion_point(field_set:f1.CarTelemetry.front_right_wheel_angle)
}

// float rear_left_wheel_angle = 13;
inline void CarTelemetry::clear_rear_left_wheel_angle() {
  _impl_.rear_left_wheel_angle_ = 0;
}
inline float CarTelemetry::_internal_rear_left_wheel_angle() const {
  return _impl_.rear_left_wheel_angle_;
}
inline float CarTelemetry::rear_left_wheel_angle() const {
  // @@protoc_insertion_point(field_get:f1.CarTelemetry.rear_left_wheel_angle)
  return _internal_rear_left_wheel_angle();
}
inline void CarTelemetry::_internal_set_rear_left_wheel_angle(float value) {
  
  _impl_.rear_left_wheel_angle_ = value;
}
inline void CarTelemetry::set_rear_left_wheel_angle(float value) {
  _internal_set_rear_left_wheel_angle(value);
  // @@protoc_insertion_point(field_set:f1.CarTelemetry.rear_left_wheel_angle)
}

// float rear_right_wheel_angle = 14;
inline void CarTelemetry::clear_rear_right_wheel_angle() {
  _impl_.rear_right_wheel_angle_ = 0;
}
inline float CarTelemetry::_internal_rear_right_wheel_angle() const {
  return _impl_.rear_right_wheel_angle_;
}
inline float CarTelemetry::rear_right_wheel_angle() const {
  // @@protoc_insertion_point(field_get:f1.CarTelemetry.rear_right_wheel_angle)
  return _internal_rear_right_wheel_angle();
}
inline void CarTelemetry::_internal_set_rear_right_wheel_angle(float value) {
  
  _impl_.rear_right_wheel_angle_ = value;
}
inline void CarTelemetry::set_rear_right_wheel_angle(float value) {
  _internal_set_rear_right_wheel_angle(value);
  // @@protoc_insertion_point(field_set:f1.CarTelemetry.rear_right_wheel_angle)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace f1

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_f1_2fcar_5ftelemetry_2eproto
